spring:
  profiles: development
  active: basic_auth_security_mock, H2_database_with_console, disable_auth_filter
---
spring:
  profiles: basic_auth_security_mock
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
security:
  basic:
    enabled: true
  headers:
    frame: false
---
spring:
  profiles: H2_database_with_console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:outcobra
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
    outcobra.server.data: debug
security:
  headers:
    frame: false
---
spring:
  profiles: MySql_database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/outcobra_a
    username: outcobra-a
    password: <todo>
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
