spring:
  profiles:
    active: development #TODO this is only temporary until issue #47 is resolved
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  h2:
    console:
      enabled: true
security:
  basic:
    enabled: false
  headers:
    frame: false
---
spring:
  profiles: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:outcobra
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: production
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/outcobra_a
      username: outcobra-a
      password: <todo>
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
